languageCode = "en-us"
theme = "vindum"
title = "Vindum"
baseurl = "http://example.org/"

PygmentsCodeFences = true
pygmentsuseclasses = true

[params]
    author = "Simon Friis Vindum"
    headline = "Blog"
    pseudo = "paldepind"
    twitter = "paldepind"
    github = "paldepind"
    linkedin = "paldepind"

[permalinks]
    post = "blog/:title"
    page = "/:title"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = "-1"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/paldepind"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/paldepind"
