languageCode = "en-us"
theme = "etch"
title = "paldepind"
baseurl = "https://monoid.dk/"

PygmentsCodeFences = true
pygmentsuseclasses = true

[params]
    author = "Simon Friis Vindum"
    headline = "Blog"
    pseudo = "paldepind"
    twitter = "paldepind"
    github = "paldepind"
    linkedin = "paldepind"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = "-1"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/paldepind"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/paldepind"
